<a href="https://colab.research.google.com/github/Tejasp9090/data_science_practice/blob/main/DS_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Science
**Numpy**

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/usr/local/lib/python3.13/dist-packages/numpy/__init__.py'>

In [5]:
np.__version__

'2.1.3'

In [6]:
# Interview Questions an numpy
# Create a numpy array
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [ ]:
# Q What is Difffrence bet* list & Numpy Array?


**Different Ways To create The array**


In [12]:
#1)
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
b=np.zeros(5,dtype=int)
b

array([0, 0, 0, 0, 0])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
b.ndim

1

In [29]:
# 2D
c=np.zeros((4,3))

In [30]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
c.ndim

2

In [31]:
# 3D
D3=np.zeros([4,2,2])

In [32]:
D3

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [35]:
# create the array of constant array
np.full((3,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])